import type { Metadata } from "next";
import "./globals.css";
import Provider from "@/src/hooks/Provider";
import { Navbar } from "@/src/components/navbar";
import { Footer } from "@/src/components/footer";


export const metadata: Metadata = {
  title: "Alpha",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       >
           <Provider>
 <Navbar/>
        {children}
        <Footer/>
           </Provider>
      </body>
    </html>
  );
}
