import type { Metadata } from "next";
import "./globals.css";
import Provider from "@/src/hooks/Provider";
import NextTopLoader from 'nextjs-toploader';

export const metadata: Metadata = {
  title: "Alpha",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       >
           <Provider>
           <NextTopLoader />
        {children}
       
           </Provider>
      </body>
    </html>
  );
}
