import type { Metadata } from "next";
import "./globals.css";
import Provider from "@/src/components/Provider";

export const metadata: Metadata = {
  title: "Alpha",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
